# Release
modrinth_id=Mk2zvcJE
mod_game_versions=1.21.1
modrinth_dependencies_fabric=P7dR8mSH(required),mOgUt4GM(optional)
modrinth_dependencies_neoforge=

# Project
version=1.0.0
group=com.bvengo
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Sound Controller: Tweaked
mod_author=BVengo, palm1
mod_id=soundcontroller
license=LGPL-3.0
credits=JustAlittleWolf, YouQi-ovo, Maganoos, lonefelidae16, eikhren, CoolAid48
description=Have complete control over the volume of all sounds played in the game.
minecraft_version_range=[1.21.1, 1.21.2)

# Fabric
fabric_version=0.101.2+1.21.1
fabric_loader_version=0.16.9
modmenu_version=11.0.4

# NeoForge
neo_form_version=1.21.1-20240808.144430
neoforge_version=21.1.1
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false