# Release
modrinth_id=6jaRrQ1v
modrinth_dependencies_fabric=P7dR8mSH(required),mOgUt4GM(optional)
modrinth_dependencies_neoforge=

# Project
version=1.0.0
group=com.bvengo
java_version=25

# Common
minecraft_version=26.1.2
mod_name=Sound Controller Tweaked
mod_author=BVengo, palm1
mod_id=soundcontroller
license=LGPL-3.0
credits=JustAlittleWolf, YouQi-ovo, Maganoos, lonefelidae16, eikhren, CoolAid48
description=Have complete control over the volume of all sounds played in the game.
minecraft_version_range=[26.1, 26.2)

# Fabric
fabric_version=0.146.1+26.1.2
fabric_loader_version=0.18.6
modmenu_version=18.0.0-alpha.8

# NeoForge
neo_form_version=26.1.2-1
neoforge_version=26.1.0.19-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false