name: Build Mod

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    name: Build JARs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read properties
        id: properties
        run: |
          MOD_NAME=$(grep 'mod_name=' gradle.properties | cut -d'=' -f2 | xargs)
          MOD_VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2 | xargs)
          GAME_VERSIONS=$(grep 'mod_game_versions=' gradle.properties | cut -d'=' -f2 | xargs)
          JAVA_VERSION=$(grep 'java_version=' gradle.properties | cut -d'=' -f2 | xargs)
          MAIN_GAME_VERSION=$(echo $GAME_VERSIONS | cut -d',' -f1)
          
          echo "mod_name=$MOD_NAME" >> $GITHUB_OUTPUT
          echo "mod_version=$MOD_VERSION" >> $GITHUB_OUTPUT
          echo "game_version=$MAIN_GAME_VERSION" >> $GITHUB_OUTPUT
          echo "java_version=$JAVA_VERSION" >> $GITHUB_OUTPUT

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ steps.properties.outputs.java_version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build mod
        run: chmod +x gradlew && ./gradlew generateChangelog && ./gradlew build

      - name: Prepare nightly builds
        run: |
          find fabric/build/libs/ -name "*.jar" -exec bash -c 'mv "$1" "${1%.jar}-nightly.jar"' _ {} \;
          find neoforge/build/libs/ -name "*.jar" -exec bash -c 'mv "$1" "${1%.jar}-nightly.jar"' _ {} \;

      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: "${{ steps.properties.outputs.mod_name }}-${{ steps.properties.outputs.mod_version }}-nightly-builds"
          path: |
            fabric/build/libs/*-nightly.jar
            neoforge/build/libs/*-nightly.jar
          if-no-files-found: error
